# Generated by Django 6.0.1 on 2026-01-08 19:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0002_recipeingredient_max_per_person_g_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_people', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=dict)),
                ('protein_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='draft', help_text='draft / confirmed / cooked', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cook_batches', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=120)),
                ('group', models.CharField(blank=True, max_length=40)),
                ('q10_g', models.FloatField()),
                ('b', models.FloatField()),
                ('c_g', models.FloatField(default=0.0)),
                ('min_per_person_g', models.FloatField(blank=True, null=True)),
                ('max_per_person_g', models.FloatField(blank=True, null=True)),
                ('pred_g', models.FloatField()),
                ('pred_kg', models.FloatField()),
                ('final_g', models.FloatField()),
                ('final_kg', models.FloatField()),
                ('was_clamped', models.BooleanField(default=False)),
                ('actual_g', models.FloatField(blank=True, null=True)),
                ('actual_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cooking.cookbatch')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'ingredient'), name='uniq_batch_ingredient')],
            },
        ),
    ]
