# Generated by Django 6.0.1 on 2026-03-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_staffprofile_global_role_branchroleassignment'),
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbatch',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='cook_batches', to='accounts.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookbatch',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_cook_batches', to='accounts.staffprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cookbatch',
            name='status',
            field=models.CharField(default='draft', help_text='draft / confirmed / cooked / final', max_length=20),
        ),
    ]
