# Generated by Django 6.0.1 on 2026-03-29 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_staffprofile_global_role_branchroleassignment'),
        ('cooking', '0002_cookbatch_branch_cookbatch_created_by_and_more'),
        ('recipes', '0002_recipeingredient_max_per_person_g_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=120)),
                ('s', models.FloatField(help_text='Learned multiplicative scale factor')),
                ('tau_days', models.FloatField(default=14.0)),
                ('sample_count', models.PositiveIntegerField(default=0, help_text='Number of log rows used for this learned scale')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_scales', to='accounts.branch')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_scales', to='recipes.recipe')),
            ],
            options={
                'ordering': ['ingredient'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'branch', 'recipe'), name='uniq_ingredient_scale_scope')],
            },
        ),
    ]
