# Generated by Django 6.0.1 on 2026-04-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_cookbatch_actuals_locked_cookbatch_actuals_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbatch',
            name='used_date',
            field=models.DateField(blank=True, help_text='Date this batch is planned to be used.', null=True),
        ),
    ]
