# Generated by Django 6.0.1 on 2026-05-09 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_branchroleassignment_role'),
        ('cooking', '0005_cookbatch_used_date'),
        ('recipes', '0004_ingredientcategory_recipeingredient_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConsumptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField(help_text='Date this daily plan is intended to be used.')),
                ('status', models.CharField(default='draft', help_text='draft / confirmed / final', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_consumption_plans', to='accounts.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_consumption_plans', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyConsumptionPlanRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_people', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=dict)),
                ('protein_type', models.CharField(blank=True, max_length=100)),
                ('cook_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plan_recipe', to='cooking.cookbatch')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cooking.dailyconsumptionplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_plan_entries', to='recipes.recipe')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyConsumptionPlanIngredientSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=120)),
                ('group', models.CharField(blank=True, max_length=40)),
                ('raw_total_g', models.FloatField(default=0.0)),
                ('raw_total_kg', models.FloatField(default=0.0)),
                ('adjusted_total_g', models.FloatField(default=0.0)),
                ('adjusted_total_kg', models.FloatField(default=0.0)),
                ('daily_factor', models.FloatField(default=1.0)),
                ('adjustment_g', models.FloatField(default=0.0)),
                ('unit_display', models.CharField(default='g', max_length=10)),
                ('adjustment_reason', models.CharField(blank=True, max_length=255)),
                ('is_shared_adjusted', models.BooleanField(default=False)),
                ('actual_total_g', models.FloatField(blank=True, null=True)),
                ('actual_total_kg', models.FloatField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_summaries', to='cooking.dailyconsumptionplan')),
            ],
            options={
                'ordering': ['ingredient'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'ingredient'), name='uniq_daily_plan_ingredient_summary')],
            },
        ),
        migrations.CreateModel(
            name='DailyPlanIngredientScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=120)),
                ('learned_factor', models.FloatField(default=1.0)),
                ('min_factor', models.FloatField(default=0.75)),
                ('max_factor', models.FloatField(default=1.05)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_plan_ingredient_scales', to='accounts.branch')),
            ],
            options={
                'ordering': ['ingredient'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'branch'), name='uniq_daily_plan_ingredient_scale_scope')],
            },
        ),
    ]
