# Generated by Django 6.0.1 on 2026-05-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_dailyconsumptionplan_dailyconsumptionplanrecipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbatch',
            name='source_type',
            field=models.CharField(choices=[('single', 'Single Consumption'), ('daily_plan', 'Daily Plan Consumption')], default='single', max_length=20),
        ),
    ]
