# Generated by Django 6.0.1 on 2026-05-09 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_branchroleassignment_role'),
        ('cooking', '0007_cookbatch_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlanIngredientScaleSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=120)),
                ('raw_total_g', models.FloatField()),
                ('adjusted_total_g', models.FloatField()),
                ('actual_total_g', models.FloatField()),
                ('observed_factor', models.FloatField(help_text='actual_total_g / raw_total_g')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_plan_ingredient_scale_samples', to='accounts.branch')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_scale_samples', to='cooking.dailyconsumptionplan')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_samples', to='cooking.dailyconsumptionplaningredientsummary')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ingredient', 'branch'], name='cooking_dai_ingredi_b87b2f_idx')],
            },
        ),
    ]
