# Generated by Django 6.0.1 on 2026-05-13 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_branchroleassignment_role'),
        ('cooking', '0008_dailyplaningredientscalesample'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySharedIngredientRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120, unique=True)),
                ('factor', models.FloatField(default=0.95)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_shared_ingredient_rules', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
    ]
