# Generated by Django 6.0.1 on 2026-03-21 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='global_role',
            field=models.CharField(choices=[('none', 'None'), ('boss', 'Boss'), ('managing_director', 'Managing Director')], default='none', max_length=50),
        ),
        migrations.CreateModel(
            name='BranchRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('branch_manager', 'Branch Manager'), ('chef', 'Chef')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='accounts.branch')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_roles', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['branch__name', 'role', 'staff_profile__full_name'],
                'constraints': [models.UniqueConstraint(fields=('staff_profile', 'branch', 'role'), name='unique_staff_branch_role')],
            },
        ),
    ]
