# Generated by Django 6.0.1 on 2026-04-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_staffprofile_global_role_branchroleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchroleassignment',
            name='role',
            field=models.CharField(choices=[('branch_manager', 'Branch Manager'), ('chef', 'Chef'), ('kitchen_staff', 'Kitchen Staff')], max_length=50),
        ),
    ]
