# Generated by Django 6.0.1 on 2026-04-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_branchroleassignment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchroleassignment',
            name='role',
            field=models.CharField(choices=[('branch_manager', 'Branch Manager'), ('chef', 'Chef'), ('kitchen_staff', 'Kitchen Staff'), ('store', 'Store')], max_length=50),
        ),
    ]
