from django.urls import path
from . import views

urlpatterns = [
    path("cooking/batches/", views.list_cook_batches, name="cooking-batch-list"),
    path(
        "cooking/batches/<int:batch_id>/",
        views.retrieve_cook_batch,
        name="cooking-batch-detail",
    ),
    path(
        "cooking/batches/<int:batch_id>/actuals/",
        views.update_cook_batch_actuals,
        name="cooking-batch-actuals",
    ),
    path(
        "cooking/batches/<int:batch_id>/post-review/",
        views.post_review_update_cook_batch,
        name="cooking-batch-post-review",
    ),
    path(
        "cooking/batches/create/", views.create_cook_batch, name="cooking-batch-create"
    ),
    path(
        "cooking/recalibrate/",
        views.recalibrate_ingredient_scales,
        name="cooking-recalibrate",
    ),
    path(
        "cooking/daily-plans/rebuild-learning/",
        views.rebuild_daily_plan_learning,
        name="daily-plan-learning-rebuild",
    ),
    path(
        "cooking/daily-shared-rules/",
        views.daily_shared_ingredient_rules,
        name="daily-shared-rules",
    ),
    path(
        "cooking/daily-shared-rules/<int:rule_id>/",
        views.daily_shared_ingredient_rule_detail,
        name="daily-shared-rule-detail",
    ),
    path(
        "batches/<int:batch_id>/lock-actuals/",
        views.lock_cook_batch_actuals,
    ),
    path(
        "cooking/daily-plans/create/",
        views.create_daily_consumption_plan_view,
        name="daily-consumption-plan-create",
    ),
    path(
        "cooking/daily-plans/",
        views.list_daily_consumption_plans,
        name="daily-consumption-plan-list",
    ),
    path(
        "cooking/daily-plans/<int:plan_id>/children/",
        views.list_daily_consumption_plan_children,
        name="daily-consumption-plan-children",
    ),
    path(
        "cooking/daily-plans/<int:plan_id>/children/<int:batch_id>/",
        views.retrieve_daily_consumption_plan_child,
        name="daily-consumption-plan-child-detail",
    ),
    path(
        "cooking/daily-plans/<int:plan_id>/actuals/",
        views.update_daily_consumption_plan_actuals,
        name="daily-consumption-plan-actuals",
    ),
    path(
        "cooking/daily-plans/<int:plan_id>/",
        views.retrieve_daily_consumption_plan,
        name="daily-consumption-plan-detail",
    ),
]
