# Generated by Django 6.0.1 on 2026-04-14 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_branchroleassignment_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cook_batch_created', 'Cook Batch Created'), ('cook_batch_actuals_updated', 'Cook Batch Actuals Updated'), ('cook_batch_finalized', 'Cook Batch Finalized'), ('ingredient_scales_recalibrated', 'Ingredient Scales Recalibrated')], max_length=100)),
                ('target_type', models.CharField(choices=[('cook_batch', 'Cook Batch'), ('recipe', 'Recipe'), ('ingredient_scale', 'Ingredient Scale'), ('system', 'System')], max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the target record if applicable.', null=True)),
                ('message', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('actor_staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='accounts.staffprofile')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='accounts.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='activity_ac_action_9760c5_idx'), models.Index(fields=['target_type', 'target_id'], name='activity_ac_target__0c7687_idx'), models.Index(fields=['branch'], name='activity_ac_branch__f66871_idx'), models.Index(fields=['processed_at'], name='activity_ac_process_db8c24_idx'), models.Index(fields=['created_at'], name='activity_ac_created_95aa6e_idx')],
            },
        ),
    ]
