# Generated by Django 6.0.1 on 2026-04-14 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_branchroleassignment_role'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activity.activityevent')),
                ('recipient_staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_staff_profile', 'is_read'], name='activity_no_recipie_745060_idx'), models.Index(fields=['event'], name='activity_no_event_i_f535c3_idx'), models.Index(fields=['created_at'], name='activity_no_created_c3c6f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'recipient_staff_profile'), name='uniq_event_recipient_notification')],
            },
        ),
    ]
