# Generated by Django 6.0.1 on 2026-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_notification_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='action',
            field=models.CharField(choices=[('cook_batch_created', 'Cook Batch Created'), ('cook_batch_actuals_updated', 'Cook Batch Actuals Updated'), ('cook_batch_finalized', 'Cook Batch Finalized'), ('cook_batch_post_review_updated', 'Cook Batch Post Review Updated'), ('ingredient_scales_recalibrated', 'Ingredient Scales Recalibrated')], max_length=100),
        ),
    ]
