# Generated by Django 6.0.1 on 2026-05-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activityevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='action',
            field=models.CharField(choices=[('cook_batch_created', 'Cook Batch Created'), ('cook_batch_actuals_updated', 'Cook Batch Actuals Updated'), ('cook_batch_finalized', 'Cook Batch Finalized'), ('daily_plan_created', 'Daily Plan Created'), ('daily_plan_actuals_updated', 'Daily Plan Actuals Updated'), ('daily_plan_finalized', 'Daily Plan Finalized'), ('cook_batch_post_review_updated', 'Cook Batch Post Review Updated'), ('ingredient_scales_recalibrated', 'Ingredient Scales Recalibrated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='target_type',
            field=models.CharField(choices=[('cook_batch', 'Cook Batch'), ('daily_plan', 'Daily Plan'), ('recipe', 'Recipe'), ('ingredient_scale', 'Ingredient Scale'), ('system', 'System')], max_length=50),
        ),
    ]
