# Generated by Django 6.0 on 2025-12-29 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('q10_g', models.FloatField()),
                ('b', models.FloatField(default=1.0)),
                ('c_g', models.FloatField(default=0.0)),
                ('group', models.CharField(choices=[('bulk', 'Bulk'), ('medium', 'Medium'), ('aromatic', 'Aromatic'), ('seasoning', 'Seasoning'), ('protein', 'Protein'), ('other', 'Other')], default='other', max_length=20)),
                ('option_group', models.CharField(blank=True, max_length=50)),
                ('option_value', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['item_no', 'id'],
                'unique_together': {('recipe', 'name', 'option_group', 'option_value')},
            },
        ),
    ]
