# Generated by Django 6.0 on 2025-12-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='max_per_person_g',
            field=models.FloatField(blank=True, help_text='Maximum grams per person (safety ceiling)', null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='min_per_person_g',
            field=models.FloatField(blank=True, help_text='Minimum grams per person (safety floor)', null=True),
        ),
    ]
