# Generated by Django 6.0.1 on 2026-04-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_branchroleassignment_role'),
        ('recipes', '0002_recipeingredient_max_per_person_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='actuals_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='actuals_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='actuals_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_recipes', to='accounts.staffprofile'),
        ),
    ]
